version: 2
jobs:
  build:
    machine:
      enabled: true
    working_directory: ~/circleci-kotlin-playground
    steps:
    - checkout
    - run:
        name: Download kotlin and kloudformation
        command: |
          mkdir -p kotlin
          cd kotlin
          curl https://github.com/JetBrains/kotlin/releases/download/v1.3.10/kotlin-compiler-1.3.10.zip -L -o kotlin.zip
          unzip kotlin.zip
          curl https://bintray.com/hexlabsio/kloudformation/download_file?file_path=io%2Fkloudformation%2Fkloudformation%2F0.1.106%2Fkloudformation-0.1.106-uber.jar -L -o kloudformation.jar
    - run:
        name: Transpile Kloudformation Stack
        command: |
          cd kotlin
          kotlinc/bin/kotlinc -classpath kloudformation.jar ../.circleci/Kloudformation.kt -include-runtime -d stack.jar
          java -classpath stack.jar:kloudformation.jar io.kloudformation.StackBuilderKt Kloudformation template.yml
          mv template.yml ..
    - store_artifacts:
        path: template.yml
    - run:
        name: Docker Build
        command: docker build -t hexlabs/kloudformation-playground:latest .

    - run:
        name: Docker Tag
        command: docker tag hexlabs/kotlin-playground:latest hexlabs/kloudformation-playground:0.1.$CIRCLE_BUILD_NUM

    - run:
        name: Docker Login
        command: docker login -u hexlabsbuilder -p $DOCKER_HUB_PASSWORD

    - run:
        name: Docker Push
        command: |
          docker push hexlabs/kloudformation-playground:latest
          docker push hexlabs/kloudformation-playground:0.1.$CIRCLE_BUILD_NUM